### ISSUE TITLE
生产环境如何配置proxyagent

### ISSUE THREAD

**Issue by itsky365** [eggjs/egg-development-proxyagent#3]
// config/plugin.js
```
exports.proxyagent = {
    enable: true,
    package: 'egg-development-proxyagent',
};
```
其他config.xx.js 中没有加配置项

本地运行 
> http_proxy=http://127.0.0.1:8888 nohup node index.js

> anyproxy --port 8888

打开浏览器 localhost:8002 查看**有**请求的数据记录

生产运行
> EGG_SERVER_ENV=prod http_proxy=http://127.0.0.1:8888 nohup node index.js

> anyproxy --port 8888

打开浏览器 localhost:8002 查看**没有**请求的数据记录

**Comment by atian25** [comment]
默认只在本地开发环境才开启，如果需要在其他环境开启，在应用的 `plugin.js` 中配置：

```js
// config/plugin.js

exports.proxyagent = {
    enable: true,
    package: 'egg-development-proxyagent',
    env: ['local', 'prod']
};
```

但我们不推荐在生产环境开启。

我们的 issue 统一反馈入口在 https://github.com/eggjs/egg/issues

晚点我会关闭掉了这个仓库的 issue 入口.
